kind: Template
apiVersion: v1
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations:
            openshift.io/imported-from: 'loadimpact/k6:latest'
          from:
            kind: DockerImage
            name: 'loadimpact/k6:latest'
          generation: null
          importPolicy: {}
          name: latest
          referencePolicy:
            type: ''
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        build: ${NAME}
      name: k6
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        build: ${NAME}
      name: ${NAME}
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: '${NAME}:${OUTPUT_TAG}'
      postCommit: {}
      resources: {}
      source:
        contextDir: k6
        git:
          ref: ${GIT_REF}
          uri: ${GIT_REPO}
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: 'k6:latest'
        type: Docker
      triggers:
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      labels:
        build: ${NAME}
      name: ${NAME}
parameters:
- name: NAME 
  value: ocp-k6
- name: OUTPUT_TAG
  value: latest
- name: GIT_REF
  value: master
- name: GIT_REPO
  value: 'https://github.com/bcgov/ocp-sso'
