kind: Template
apiVersion: v1
objects:
  - apiVersion: batch/v1
    kind: Job
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          volumes:
            - name: k6-config
              configMap:
                name: ${NAME}-config
            - name: k6-logs
              emptyDir: {}
          containers:
            - image: ${IMAGE_REGISTRY}/${IMAGE_NAMESPACE}/${IMAGE_TAG}
              name: ${NAME}
              env:
                - name: SSO_BASE_URL
                  value: ${SSO_BASE_URL}
                - name: K6_HTTP_DEBUG
                  value: ${HTTP_DEBUG}
                - name: LOG_OUTPUT_PATH
                  value: ${LOG_OUTPUT_PATH}
              resources:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 50m
                  memory: 25Mi
              volumeMounts:
                - name: k6-config
                  mountPath: /var/opt/config
                - name: k6-logs
                  mountPath: ${LOG_OUTPUT_PATH}
          restartPolicy: Never
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
        component: ${NAME}-job
        group: sso-k6
  - apiVersion: v1
    data:
      index.json: |-
        {
          "vus": "10",
          "duration": "30s"
        }
    kind: ConfigMap
    metadata:
      creationTimestamp: null
      name: ${NAME}-config
      labels:
        app: ${NAME}
        group: sso-k6
        component: ${NAME}-configmap
parameters:
- name: NAME
  value: sso-k6
- name: IMAGE_TAG
  value: sso-k6:latest
- name: IMAGE_NAMESPACE
  value: devops-sso-tools
- name: IMAGE_REGISTRY
  value: docker-registry.default.svc:5000
- name: SSO_BASE_URL
  description: the fully qualified sso base url (including https)
  required: true
- name: LOG_OUTPUT_PATH
  description: the path json logs are written to inside of the pod
  value: /tmp/logs
- name: HTTP_DEBUG
  description: enable http debug logging in the k6 pod
  value: "false"

