# VARS
# HPA_NAME: string
# SSO_DC_NAME: string
# TARGET_NAMESPACE: string
# _action: string (create|delete)
- name: creating HPA
  shell: | 
    oc -n {{ TARGET_NAMESPACE}} process -f ../openshift/hpa.yaml -p NAME={{ HPA_NAME }} -p TARGET_DC_NAME={{ SSO_DC_NAME }} | \
    oc -n {{ TARGET_NAMESPACE }} apply -f - 
  when: _action == 'create'


- name: checking if HPA exists
  k8s_info:
    api_version: v1
    kind: "HorizontalPodAutoscaler"
    name: "{{ HPA_NAME }}"
    namespace: "{{ TARGET_NAMESPACE }}"
  register: hpa
  when: _action == 'delete'
- name: deleting HPA
  shell: oc delete hpa/{{ HPA_NAME }} -n {{ TARGET_NAMESPACE}}
  when: _action == 'delete' and hpa.resources|length > 0
