# vars 
# PATRONI_SS_NAME: string (the stateful set name)
# TARGET_NAMESPACE: string the target namespace to scale down the replicas

- name: Scaling {{ PATRONI_SS_NAME }} to 0 pods 
  shell: oc -n {{ TARGET_NAMESPACE }} scale statefulset/{{ PATRONI_SS_NAME }} --replicas=0 

- name: wait for patroni to be at 0 replicas 
  include_tasks: wait_for_rollout.yml
  vars:
    delay: 45
    KIND: StatefulSet
    OBJECT_NAME: "{{ PATRONI_SS_NAME }}" 
    DESIRED_REPLICAS: 0

- name: Remove {{ PATRONI_SS_NAME }} patroni status configmap
  shell: oc -n {{ TARGET_NAMESPACE }} delete configmap {{ PATRONI_SS_NAME }}-config {{ PATRONI_SS_NAME }}-leader 
  ignore_errors: yes