## Waits for a statefulset or deploymentconfig to reach a desired set of replicas

## Vars:
# KIND: string
# delay: number
# OPENSHIFT_SERVER_URL: string
# TARGET_NAMESPACE: string
# OBJECT_NAME: string
# DESIRED_REPLICAS: number

- name: get token
  shell: oc whoami -t 
  register: token

- name: setting fact for KIND to use with api
  set_fact:
    _kind: "{% if KIND|upper == 'STATEFULSET' %}statefulsets{% elif KIND|upper == 'DEPLOYMENTCONFIG' %}deploymentconfigs{% endif %}"
    _api_type: "{% if KIND|upper == 'STATEFULSET' %}apps{% elif KIND|upper == 'DEPLOYMENTCONFIG' %}apps.openshift.io{% endif %}"
- name: Wait for "{{ KIND }}" object {{ OBJECT_NAME }} pods to be {{ DESIRED_REPLICAS }} into ready state in {{ TARGET_NAMESPACE }} 
  uri:
    url: "{{ OPENSHIFT_SERVER_URL }}/apis/{{ _api_type }}/v1/namespaces/{{ TARGET_NAMESPACE }}/{{ _kind }}/{{ OBJECT_NAME }}"
    method: GET
    headers:
      Authorization: "Bearer {{ token.stdout }}"
      Accept: 'application/json'
  register: result
  # known bug here, it doesn't wait for scaling to 0 replicas because there is no state to verify pods are terminating
  until: ((result.json.status.readyReplicas is defined) and (result.json.status.readyReplicas == result.json.spec.replicas) and (result.json.spec.replicas == DESIRED_REPLICAS)) or (DESIRED_REPLICAS == 0 and result.json.status.readyReplicas is not defined)
  delay: "{{ delay | default(15) }}"
  retries: 45
  ignore_errors: True

- debug: 
    msg:
      - "--------- {{ KIND }} must be DeploymentConfig or StatefulSet---------"
  when: not _kind